# Generated by Django 4.1 on 2022-09-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='grower_id',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='grower_id',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='fname',
            field=models.CharField(default='First', max_length=50),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='lname',
            field=models.CharField(default='Last', max_length=50),
        ),
    ]
