# Generated by Django 4.1 on 2022-09-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_farmer_grower_id_alter_farm_grower_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.EmailField(max_length=254)),
                ('web', models.URLField()),
            ],
            options={
                'db_table': 'partners',
            },
        ),
    ]
