# Generated by Django 4.1 on 2022-09-21 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='farm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portal.farm', verbose_name='ForeignKey'),
            preserve_default=False,
        ),
    ]
