# Generated by Django 4.1 on 2022-09-21 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_farmer_farm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmer',
            old_name='farm',
            new_name='farmID',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='grower_id',
        ),
    ]
