# Generated by Django 4.1 on 2022-09-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_rename_farm_farmer_farmid_remove_farmer_grower_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='logo',
            field=models.ImageField(default=1, upload_to=None),
            preserve_default=False,
        ),
    ]
