# Generated by Django 4.1 on 2022-09-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_alter_farm_options_alter_farmer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='email',
            field=models.EmailField(default='fname.last@email.com', max_length=254, verbose_name='Email'),
        ),
    ]
