# Generated by Django 4.1 on 2022-09-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_farmer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='email',
            field=models.EmailField(db_index=True, default='fname.last@email.com', max_length=254, unique=True, verbose_name='Email'),
        ),
    ]
